name: Deploy to RabbitMQ

on:
  push:
    branches: main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Publish message to RabbitMQ
        uses: knittotextile/rabbitmq-publish-message@v0
        with:
          app_id: remote-build
          rabbitmq_host: armadillo.rmq.cloudamqp.com/jriwfxqv
          rabbitmq_username: jriwfxqv
          rabbitmq_password: 3rPvImvXujYDXHIk4fWadle7bDkudzyM
          queue_name: Queue_Jenkins
          message: >
            {
              "project": "test-project",
              "token": "8BWiBG4ybljE5yrz1vksrFxcZQ1x8ftKQZvwF7z5IP3rpcF5qKBj7OBUJD90iqfq5WVDMkOxgYBS3LfwySGlj8SedPm7b4b6UDbX",
              "parameter": []
            }
        # with:
        #   MESSAGE: >
        #     {
        #         "project": "test-project",
        #         "token": "8BWiBG4ybljE5yrz1vksrFxcZQ1x8ftKQZvwF7z5IP3rpcF5qKBj7OBUJD90iqfq5WVDMkOxgYBS3LfwySGlj8SedPm7b4b6UDbX",
        #         "parameter": []
        #     }
        #   QUEUENAME: "Queue_Jenkins"
        #   HEADERS: ""
        #   RABBITMQ_HOST: "armadillo.rmq.cloudamqp.com"
        #   RABBITMQ_VHOSTNAME: "jriwfxqv"
        #   RABBITMQ_USERNAME: "jriwfxqv"
        #   RABBITMQ_PASSWORD: "3rPvImvXujYDXHIk4fWadle7bDkudzyM"
