name: Deploy to RabbitMQ

on:
  push:
    branches: main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Publish message to RabbitMQ
        uses: knittotextile/rabbitmq-publish-message@v0
        with:
          app_id: remote-build
          rabbitmq_host: "{{ secret.RABBITMQ_HOST }}"
          rabbitmq_username: "{{ secret.RABBITMQ_USER }}"
          rabbitmq_vhostname: "{{ secret.RABBITMQ_VHOST }}"
          rabbitmq_password: "{{ secret.RABBITMQ_PASS }}"
          queue_name: "Queue_Jenkins"
          message: >
            {
              "project": "test-project",
              "token": "{{ secret.JENKINS_RABBITMQ_TOKEN_PROD }}",
              "parameter": []
            }
